version: "3.8"

networks: 
  rrenja:

services:
#---------------------- Backend----------------------------# 
#- PHP and Nginx                                           #
#----------------------------------------------------------#
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/app:/var/www
    ports:
      - "9000:80"
    working_dir: /var/www
    networks:
      - rrenja

